"""Add health_score column to Analysis

Revision ID: 3f7e8e6a563c
Revises: ec7cea91b0d6
Create Date: 2026-09-20 02:15:32.171230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7e8e6a563c'
down_revision = 'ec7cea91b0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_score', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('health_score')

    # ### end Alembic commands ###
