"""Add UserActivity and User.is_blocked

Revision ID: 52b9dc0e5123
Revises: 
Create Date: 2026-09-12 20:40:20.184725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b9dc0e5123'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.create_index('idx_user_activity_recent', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activities_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activities_created_at'))
        batch_op.drop_index('idx_user_activity_recent')

    op.drop_table('user_activities')
    # ### end Alembic commands ###
