"""Add composite indexes for income and expense

Revision ID: a812d1a3180a
Revises: a966ddcb2038
Create Date: 2026-10-03 21:37:54.091312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a812d1a3180a'
down_revision = 'a966ddcb2038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expense_user_category_date', ['user_id', 'category', 'date'], unique=False)

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.create_index('ix_income_user_type_date', ['user_id', 'income_type', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_index('ix_income_user_type_date')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expense_user_category_date')

    # ### end Alembic commands ###
